#pragma once
#include <Arduino.h>
namespace thermal {
static const char WebUi[] PROGMEM=R"THERMAL(<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Thermal camera settings</title><style>
:root{color-scheme:dark;font:16px system-ui,sans-serif;background:#11151b;color:#e5eef5}body{max-width:1100px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;gap:16px}h1{font-size:28px;margin-bottom:6px}h2{font-size:18px}p{color:#9db0c0;line-height:1.5}.layout{display:grid;grid-template-columns:1.2fr 1fr;gap:22px}.panel{background:#1b222c;border:1px solid #34414f;padding:20px;border-radius:12px}#view{position:relative;aspect-ratio:4/3;background:#090c10}#feed,canvas{position:absolute;width:100%;height:100%;inset:0}canvas{touch-action:none;cursor:crosshair}#stale{position:absolute;inset:0;display:grid;place-content:center;background:#111b;font-weight:600;pointer-events:none}.stats{display:flex;flex-wrap:wrap;gap:12px;padding:14px 0}.badge{padding:5px 10px;border-radius:6px;background:#27374b}label{display:block;margin:12px 0 4px;font-size:14px;color:#bac8d3}input,select{box-sizing:border-box;width:100%;padding:9px;background:#101720;border:1px solid #526172;border-radius:5px;color:inherit;font:inherit}input[type=checkbox]{width:auto}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}button,a.button{display:inline-block;cursor:pointer;background:#54cee8;color:#072029;border:0;padding:10px 14px;border-radius:6px;margin:14px 6px 0 0;font-weight:600;text-decoration:none}button.secondary{background:#344455;color:#fff}details{border-top:1px solid #34414f;margin-top:18px;padding-top:12px}summary{cursor:pointer}#message{min-height:24px;white-space:pre-line}#test{color:#ff7ded;font-weight:bold}small{color:#9db0c0}pre{white-space:pre-wrap;font-size:12px;max-height:220px;overflow:auto}@media(max-width:760px){.layout{grid-template-columns:1fr}body{padding:14px}header{align-items:start}}
</style><header><h1>Camera settings</h1><a class="button" href="/">Thermal viewer</a></header><p>Draw an area on the image to monitor warm-object presence.</p><p id="test" hidden>TEST PATTERN &middot; Synthetic temperatures &middot; MQTT disabled</p>
<div class="layout"><section class="panel"><div id="view"><img id="feed" alt="Live thermal image"><canvas id="roi" width="320" height="240"></canvas><div id="stale">Connecting to camera...</div></div>
<div class="stats"><span class="badge" id="state">Unavailable</span><span id="temperature">&mdash;</span><span id="fps">&mdash; FPS</span></div><div class="stats"><span id="smallState">Small: unavailable</span><span id="largeState">Large: unavailable</span></div><small id="health">Connecting...</small><br><button type="button" id="learn" class="secondary">Relearn empty scene</button><a class="button" href="/snapshot.jpg" target="_blank" rel="noopener">Snapshot</a><p>Keep the region empty while learning. Stationary warm objects remain occupied. Sun-warmed surfaces can also trigger detection.</p><details><summary>Device diagnostics</summary><pre id="diagnostics"></pre></details></section>
<section class="panel"><form id="settings"><h2>Image</h2><label for="palette">Thermal colour palette</label><select id="palette"><option value="fire">Fire</option><option value="ironbow">Ironbow</option><option value="rainbow">Rainbow</option><option value="white_hot">White hot</option><option value="black_hot">Black hot</option></select><label><input id="flip_horizontal" type="checkbox"> Flip image horizontally</label><small>Image settings apply to the viewer, snapshots and USB when saved.</small>
<h2>Detection</h2><div class="row"><div><label for="delta_c">Above background (&deg;C)</label><input id="delta_c" type="number" min="0.2" max="100" step="0.1" required></div><div><label for="min_pixels">Minimum connected pixels</label><input id="min_pixels" type="number" min="1" max="4960" required></div></div>
<label for="large_min_pixels">Large object starts at (connected pixels)</label><input id="large_min_pixels" type="number" min="1" max="4960" required><small id="sizeHelp"></small><p>Size is measured in the thermal image, not real-world dimensions. Touching regions merge; separate small and large regions can trigger both channels.</p>
<div class="row"><div><label for="activate_ms">Activation delay (ms)</label><input id="activate_ms" type="number" min="0" max="60000" step="100" required></div><div><label for="clear_ms">Clear delay (ms)</label><input id="clear_ms" type="number" min="0" max="60000" step="100" required></div></div><label for="learn_ms">Background learning (ms)</label><input id="learn_ms" type="number" min="1000" max="120000" step="1000" required><p id="roiText"></p>
<details id="wifiSettings"><summary>Wi-Fi</summary><label for="ssid">Network name</label><input id="ssid" maxlength="32" autocomplete="off"><label for="wifi_password">New password (leave blank to keep)</label><input id="wifi_password" type="password" maxlength="63" autocomplete="new-password"><label><input id="clearWifiPassword" type="checkbox"> Use an open network / clear saved password</label></details>
<details><summary>MQTT &amp; Home Assistant</summary><label for="broker">Broker hostname or IPv4 (blank disables MQTT)</label><input id="broker" maxlength="127"><div class="row"><div><label for="port">Port</label><input id="port" type="number" min="1" max="65535" required></div><div><label for="mqtt_user">Username</label><input id="mqtt_user" maxlength="64" autocomplete="off"></div></div><label for="mqtt_password">New password (leave blank to keep)</label><input id="mqtt_password" type="password" maxlength="128" autocomplete="new-password"><label><input id="clearMqttPassword" type="checkbox"> Clear saved MQTT password</label><label for="topic">Topic prefix</label><input id="topic" maxlength="128" required><label><input id="ha_discovery" type="checkbox"> Home Assistant auto-discovery</label><p>Uses the same broker as Home Assistant. Creates Occupancy, Small objects and Large objects sensors using the default homeassistant discovery prefix. Learning and sensor faults appear as unavailable.</p><small>To remove discovered entities, turn discovery off and save while the broker remains configured.</small></details>
<button id="save" type="submit">Save settings</button><div id="message" role="status" aria-live="polite"></div></form></section></div>
<script>
const $=id=>document.getElementById(id),canvas=$('roi'),ctx=canvas.getContext('2d');
let area={x:0,y:0,width:80,height:62},anchor=null,started=false,lastFrame=-1,frameAt=0,nextStream=0,displayFlip=false;
const numeric=['delta_c','min_pixels','large_min_pixels','activate_ms','clear_ms','learn_ms','port'];
const strings=['ssid','broker','mqtt_user','topic','palette'];
function sizeHelp(){const min=Number($('min_pixels').value),large=Number($('large_min_pixels').value);$('sizeHelp').textContent=large>min?'Small: '+min+'-'+(large-1)+' pixels. Large: '+large+' or more.':'All qualifying regions are large; increase the cutoff to enable small-object alerts.'}
$('min_pixels').oninput=sizeHelp;$('large_min_pixels').oninput=sizeHelp;
function draw(){ctx.clearRect(0,0,320,240);ctx.strokeStyle='#53dfff';ctx.lineWidth=2;const x=displayFlip?80-area.x-area.width:area.x;ctx.strokeRect(5+x*310/80,area.y*240/62,area.width*310/80,area.height*240/62);$('roiText').textContent='ROI: '+area.x+', '+area.y+' / '+area.width+' x '+area.height+' thermal pixels'}
function point(e){let b=canvas.getBoundingClientRect();const x=Math.max(0,Math.min(79,Math.floor(((e.clientX-b.left)*320/b.width-5)*80/310)));return {x:displayFlip?79-x:x,y:Math.max(0,Math.min(61,Math.floor((e.clientY-b.top)*62/b.height)))}}
canvas.onpointerdown=e=>{anchor=point(e);canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(!anchor)return;let p=point(e);area={x:Math.min(p.x,anchor.x),y:Math.min(p.y,anchor.y),width:Math.abs(p.x-anchor.x)+1,height:Math.abs(p.y-anchor.y)+1};draw()};
canvas.onpointerup=e=>{if(anchor){canvas.onpointermove(e);anchor=null}};canvas.onpointercancel=()=>anchor=null;
async function request(path,options={}){const r=await fetch(path,{cache:'no-store',...options});let j=await r.json();if(!r.ok)throw Error(j.error||r.statusText);return j}
async function load(){try{let c=await request('/api/config');for(let k of [...numeric,...strings])$(k).value=c[k];displayFlip=!!c.flip_horizontal;$('flip_horizontal').checked=displayFlip;$('ha_discovery').checked=c.ha_discovery;area=c.roi;draw();sizeHelp();if(!c.ssid)$('wifiSettings').open=true;$('message').textContent=''}catch(e){$('message').textContent=e.message;setTimeout(load,3000)}}
$('settings').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{let c={roi:area,flip_horizontal:$('flip_horizontal').checked,ha_discovery:$('ha_discovery').checked};for(let k of numeric)c[k]=Number($(k).value);for(let k of strings)c[k]=$(k).value;for(let [key,clear]of [['wifi_password','clearWifiPassword'],['mqtt_password','clearMqttPassword']])if($(key).value||$(clear).checked)c[key]=$(clear).checked?'':$(key).value;await request('/api/config',{method:'PUT',headers:{'Content-Type':'application/json','X-Thermal-Request':'1'},body:JSON.stringify(c)});displayFlip=c.flip_horizontal;draw();$('feed').removeAttribute('src');started=false;nextStream=0;$('message').textContent='Saved. Background learning restarts. Wi-Fi changes may require reconnecting.';$('wifi_password').value='';$('mqtt_password').value='';$('clearWifiPassword').checked=false;$('clearMqttPassword').checked=false}catch(e){$('message').textContent=e.message}finally{$('save').disabled=false}};
$('learn').onclick=async()=>{try{await request('/api/relearn',{method:'POST',headers:{'X-Thermal-Request':'1'}});$('message').textContent='Learning: keep the monitored area empty.'}catch(e){$('message').textContent=e.message}};
function stream(){if(Date.now()<nextStream)return;nextStream=Date.now()+5000;$('feed').src='/stream.mjpg?t='+Date.now();started=true}
$('feed').onerror=()=>{started=false};
async function poll(){try{const s=await request('/api/status');if(s.frames!==lastFrame){lastFrame=s.frames;frameAt=Date.now()}const fresh=s.sensor_ready&&s.frame_age_ms<1000&&s.video_enabled&&Date.now()-frameAt<1500;$('stale').style.display=fresh?'none':'grid';$('stale').textContent=s.video_enabled===false?'Video paused':s.sensor_error==='none'?'Waiting for fresh video':s.sensor_error;$('state').textContent=s.sensor_warmup_ms>0?'Warming sensor: '+Math.ceil(s.sensor_warmup_ms/1000)+' s':s.state;$('fps').textContent=s.video_fps.toFixed(1)+' video FPS';$('temperature').textContent=fresh?s.min_c.toFixed(1)+' - '+s.max_c.toFixed(1)+' C':'--';$('smallState').textContent='Small: '+s.small.state+' ('+s.small.pixels+' px)';$('largeState').textContent='Large: '+s.large.state+' ('+s.large.pixels+' px)';$('health').textContent='Wi-Fi: '+(s.wifi_connected?'connected':'setup')+' / MQTT: '+(s.mqtt_connected?'connected':s.mqtt_configured?'disconnected':'disabled')+' / USB: '+s.usb;$('test').hidden=!s.test_pattern;$('diagnostics').textContent=JSON.stringify(s,null,2);if(fresh&&!started)stream();if(!fresh){started=false;$('feed').removeAttribute('src')}}catch(e){$('stale').style.display='grid';$('stale').textContent='Camera connection lost';$('health').textContent=e.message;started=false;$('feed').removeAttribute('src')}setTimeout(poll,750)}
load();poll();
</script></html>)THERMAL";
}
